### ISSUE TITLE
Add support for animated QR-codes

### ISSUE THREAD

**Issue by ullgren** [sweid4keycloak/bankid4keycloak#31]
**Describe the feature request**

Support for animated QR-codes was added in version 5.1 of the RP web service API. It will become required for starting the BankID app on another unit May 1st 2024

See https://www.bankid.com/foretag/stark-koppling

## Tasks

- [x] Add support for handling `qrStartToken` and `qrStartSecret` in the auth response
- [x] Change how the QR code is generate to use t[he new algorithm](https://www.bankid.com/utvecklare/guider/teknisk-integrationsguide/qrkoder)
- [x] Add javascript to the login page to refresh the QR code every second

**Comment by qvicksilver** [comment]
Closed by #35
